import type { Brand, Product } from "@/lib/types";

export const seedBrands: Brand[] = [
  // ── Animal health principals (EVR main site) ──
  { id: "br-1", name: "Boehringer Ingelheim", logo_url: "/images/partners/boehringer.png", categories: ["livestock", "pet-consumables"] },
  { id: "br-2", name: "Zoetis", logo_url: "/images/partners/zoetis.png", categories: ["livestock", "pet-consumables"] },
  { id: "br-3", name: "MSD Animal Health", logo_url: "/images/partners/msd.png", categories: ["livestock", "pet-consumables"] },
  { id: "br-4", name: "Elanco", logo_url: "/images/partners/elanco.png", categories: ["livestock", "pet-consumables"] },
  { id: "br-5", name: "Cargill", logo_url: "/images/partners/cargill.jpg", categories: ["livestock"] },
  { id: "br-6", name: "Hipra", logo_url: "/images/partners/hipra.jpg", categories: ["livestock", "pet-consumables"] },
  { id: "br-7", name: "Virbac", logo_url: "/images/partners/virbac.png", categories: ["pet-consumables"] },
  // ── Equipment principals (Pet Multilines) ──
  { id: "br-8", name: "Sontu", logo_url: "/images/partners/sontu.png", categories: ["equipment"] },
  { id: "br-9", name: "Edan", logo_url: "/images/partners/edan.png", categories: ["equipment"] },
  { id: "br-10", name: "RWD", logo_url: "/images/partners/rwd.jpg", categories: ["equipment"] },
  { id: "br-11", name: "Browiner", logo_url: "/images/partners/browiner.png", categories: ["equipment"] },
  { id: "br-12", name: "Aohua", logo_url: "/images/partners/aohua.png", categories: ["equipment"] },
  { id: "br-13", name: "Bizvet", logo_url: "/images/partners/bizvet.png", categories: ["equipment"] },
  { id: "br-14", name: "Infinnomed", logo_url: "/images/partners/infinnomed.png", categories: ["equipment"] },
  { id: "br-15", name: "Manpharma", logo_url: "/images/partners/manpharma.png", categories: ["equipment"] },
  { id: "br-16", name: "Pretta", logo_url: "/images/partners/pretta.png", categories: ["equipment"] },
  { id: "br-17", name: "Tootoo", logo_url: "/images/partners/tootoo.png", categories: ["equipment"] },
  { id: "br-18", name: "Willway", logo_url: "/images/partners/willway.png", categories: ["equipment"] },
];

export const seedProducts: Product[] = [
  // ─── Livestock ────────────────────────────────────────────────
  {
    id: "pl-1",
    slug: "agrivax-nd-ib-vaccine",
    name: "AgriVax ND-IB Live Vaccine",
    category: "livestock",
    subcategory: "Poultry",
    brand: "AgriVax Biologics",
    short_description:
      "Combined Newcastle Disease and Infectious Bronchitis live vaccine for broilers and layers.",
    description:
      "AgriVax ND-IB is a freeze-dried live vaccine providing early, reliable protection against Newcastle Disease and Infectious Bronchitis in commercial poultry. Suitable for day-old chicks via spray or eye-drop administration, with booster programs for layers and breeders. Supplied in 1,000-dose and 2,500-dose vials with full cold-chain handling from our warehouse to your farm.",
    specs: [
      { label: "Presentation", value: "Freeze-dried vial, 1,000 / 2,500 doses" },
      { label: "Administration", value: "Spray, eye-drop, or drinking water" },
      { label: "Target Species", value: "Broilers, layers, breeders" },
      { label: "Storage", value: "2–8°C, protect from light" },
    ],
    images: [],
    brochure_url: null,
    featured: true,
    best_seller: false,
    active: true,
  },
  {
    id: "pl-2",
    slug: "vetnova-amoxi-pro-500",
    name: "VetNova Amoxi-Pro 500 WSP",
    category: "livestock",
    subcategory: "Swine",
    brand: "VetNova Animal Health",
    short_description:
      "Amoxicillin 500 mg/g water-soluble powder for respiratory and enteric infections in swine and poultry.",
    description:
      "Amoxi-Pro 500 is a broad-spectrum amoxicillin water-soluble powder trusted by commercial swine and poultry operations for the treatment of susceptible respiratory, enteric, and systemic bacterial infections. Highly stable in drinking water systems and available in 100 g sachets and 1 kg tubs. Always use under the supervision of a licensed veterinarian and observe withdrawal periods.",
    specs: [
      { label: "Active Ingredient", value: "Amoxicillin trihydrate 500 mg/g" },
      { label: "Presentation", value: "100 g sachet / 1 kg tub" },
      { label: "Administration", value: "Drinking water" },
      { label: "Target Species", value: "Swine, poultry" },
    ],
    images: [],
    brochure_url: null,
    featured: false,
    best_seller: true,
    active: true,
  },
  {
    id: "pl-3",
    slug: "philfarm-vitaboost-ade-forte",
    name: "PhilFarm VitaBoost ADE Forte Injectable",
    category: "livestock",
    subcategory: "Cattle",
    brand: "PhilFarm Nutrition",
    short_description:
      "High-potency Vitamin A, D3, and E injectable for growth, fertility, and stress recovery in large animals.",
    description:
      "VitaBoost ADE Forte delivers concentrated vitamins A, D3, and E in a single well-tolerated injection — supporting growth performance, reproductive efficiency, immune response, and recovery from transport or disease stress in cattle, carabao, goats, and swine. A staple in breeding and fattening programs nationwide.",
    specs: [
      { label: "Composition", value: "Vit. A 500,000 IU, D3 75,000 IU, E 50 mg per mL" },
      { label: "Presentation", value: "100 mL multi-dose vial" },
      { label: "Administration", value: "Intramuscular injection" },
      { label: "Target Species", value: "Cattle, carabao, goats, swine" },
    ],
    images: [],
    brochure_url: null,
    featured: true,
    best_seller: true,
    active: true,
  },
  {
    id: "pl-4",
    slug: "bioshield-ferro-plus-b12",
    name: "BioShield Ferro-Plus B12 Injectable",
    category: "livestock",
    subcategory: "Swine",
    brand: "BioShield Animal Health",
    short_description:
      "Iron dextran with Vitamin B12 for the prevention of piglet anemia and stronger early growth.",
    description:
      "Ferro-Plus B12 combines 200 mg/mL iron dextran with Vitamin B12 to prevent iron-deficiency anemia in newborn piglets and support vigorous early growth. Smooth, fast-absorbing formulation with excellent injection-site tolerance. A foundational product for every farrowing program.",
    specs: [
      { label: "Composition", value: "Iron (as dextran) 200 mg/mL + Vit. B12" },
      { label: "Presentation", value: "100 mL vial" },
      { label: "Dosage", value: "1–2 mL IM on day 3 of life" },
      { label: "Target Species", value: "Piglets, calves" },
    ],
    images: [],
    brochure_url: null,
    featured: false,
    best_seller: false,
    active: true,
  },
  {
    id: "pl-5",
    slug: "philfarm-electrolyte-plus",
    name: "PhilFarm ElectroLyte Plus",
    category: "livestock",
    subcategory: "Poultry",
    brand: "PhilFarm Nutrition",
    short_description:
      "Electrolytes with Vitamin C for heat stress, transport stress, and post-vaccination recovery.",
    description:
      "ElectroLyte Plus rapidly replaces electrolytes lost during heat stress, transport, and disease challenge, with added Vitamin C and dextrose for energy support. Essential during the Philippine summer months and any stress event — mixing readily in drinking water for poultry, swine, and ruminants.",
    specs: [
      { label: "Composition", value: "Na, K, Mg, Cl electrolytes + Vit. C + dextrose" },
      { label: "Presentation", value: "250 g / 1 kg pouch" },
      { label: "Administration", value: "Drinking water" },
      { label: "Target Species", value: "Poultry, swine, ruminants" },
    ],
    images: [],
    brochure_url: null,
    featured: false,
    best_seller: true,
    active: true,
  },
  {
    id: "pl-6",
    slug: "vetnova-levaclear-drench",
    name: "VetNova LevaClear Oral Drench",
    category: "livestock",
    subcategory: "Goats",
    brand: "VetNova Animal Health",
    short_description:
      "Levamisole HCl broad-spectrum dewormer for goats, sheep, and cattle.",
    description:
      "LevaClear is a ready-to-use levamisole oral drench effective against mature and immature gastrointestinal roundworms and lungworms in goats, sheep, and cattle. Accurate dosing syringe included with every bottle. An affordable cornerstone of small-ruminant parasite control programs.",
    specs: [
      { label: "Active Ingredient", value: "Levamisole HCl 75 mg/mL" },
      { label: "Presentation", value: "500 mL / 1 L bottle" },
      { label: "Administration", value: "Oral drench" },
      { label: "Target Species", value: "Goats, sheep, cattle" },
    ],
    images: [],
    brochure_url: null,
    featured: false,
    best_seller: false,
    active: true,
  },
  {
    id: "pl-7",
    slug: "bioshield-farmguard-disinfectant",
    name: "BioShield FarmGuard Broad-Spectrum Disinfectant",
    category: "livestock",
    subcategory: "Farm Management",
    brand: "BioShield Animal Health",
    short_description:
      "Glutaraldehyde + quaternary ammonium disinfectant for housing, equipment, footbaths, and vehicles.",
    description:
      "FarmGuard is a professional-grade biosecurity disinfectant combining glutaraldehyde and quaternary ammonium compounds, proven effective against major viral, bacterial, and fungal pathogens of poultry and swine — including those relevant to ASF and AI biosecurity protocols. For housing, equipment, footbaths, wheel dips, and vehicle spraying.",
    specs: [
      { label: "Composition", value: "Glutaraldehyde 15% + QAC 10%" },
      { label: "Dilution", value: "1:200 – 1:400 depending on application" },
      { label: "Presentation", value: "1 L / 5 L container" },
      { label: "Applications", value: "Housing, footbaths, vehicles, hatcheries" },
    ],
    images: [],
    brochure_url: null,
    featured: true,
    best_seller: false,
    active: true,
  },
  {
    id: "pl-8",
    slug: "philfarm-proboost-premix",
    name: "PhilFarm ProBoost Performance Premix",
    category: "livestock",
    subcategory: "Cattle",
    brand: "PhilFarm Nutrition",
    short_description:
      "Vitamin-mineral feed premix that maximizes growth and feed efficiency in fattening programs.",
    description:
      "ProBoost is a complete vitamin and trace-mineral premix formulated for Philippine feeding conditions, supporting optimal daily gain, feed conversion, and overall herd vitality in cattle and swine fattening programs. Blends uniformly in home-mixed and commercial rations.",
    specs: [
      { label: "Composition", value: "Vitamins A, D3, E, K, B-complex + chelated minerals" },
      { label: "Inclusion Rate", value: "2.5 kg per ton of feed" },
      { label: "Presentation", value: "25 kg bag" },
      { label: "Target Species", value: "Cattle, swine" },
    ],
    images: [],
    brochure_url: null,
    featured: false,
    best_seller: false,
    active: true,
  },

  // ─── Pet Consumables ─────────────────────────────────────────
  {
    id: "pp-1",
    slug: "petvital-tickaway-spot-on",
    name: "PetVital TickAway Spot-On",
    category: "pet-consumables",
    subcategory: "Anti-tick & Flea",
    brand: "PetVital",
    short_description:
      "Fast-acting fipronil spot-on treatment against ticks, fleas, and lice for dogs and cats.",
    description:
      "TickAway Spot-On delivers month-long protection against ticks, fleas, and biting lice with a single easy application. Waterproof after 48 hours and safe for puppies and kittens from 8 weeks of age. Available in size-specific pipettes for accurate, stress-free dosing — a bestseller in clinics and grooming salons nationwide.",
    specs: [
      { label: "Active Ingredient", value: "Fipronil 10% w/v" },
      { label: "Presentation", value: "Pipettes for S / M / L / XL dogs & cats" },
      { label: "Protection", value: "Up to 4 weeks per application" },
      { label: "Minimum Age", value: "8 weeks" },
    ],
    images: [],
    brochure_url: null,
    featured: true,
    best_seller: true,
    active: true,
  },
  {
    id: "pp-2",
    slug: "nutripaws-total-dewormer",
    name: "NutriPaws Total Dewormer Tablets",
    category: "pet-consumables",
    subcategory: "Dewormers",
    brand: "NutriPaws",
    short_description:
      "Broad-spectrum deworming tablets covering roundworms, hookworms, whipworms, and tapeworms.",
    description:
      "NutriPaws Total is a palatable, scored deworming tablet combining pyrantel, praziquantel, and febantel for complete coverage of the most common intestinal parasites of dogs. Simple weight-based dosing makes it ideal for clinic dispensing and retail. Liver-flavored for easy acceptance.",
    specs: [
      { label: "Composition", value: "Pyrantel + Praziquantel + Febantel" },
      { label: "Dosage", value: "1 tablet per 10 kg body weight" },
      { label: "Presentation", value: "Blister of 4 / box of 100" },
      { label: "Target Species", value: "Dogs" },
    ],
    images: [],
    brochure_url: null,
    featured: false,
    best_seller: true,
    active: true,
  },
  {
    id: "pp-3",
    slug: "petvital-multivit-syrup",
    name: "PetVital MultiVit Syrup",
    category: "pet-consumables",
    subcategory: "Vitamins",
    brand: "PetVital",
    short_description:
      "Complete daily multivitamin syrup with taurine and lysine for dogs and cats of all ages.",
    description:
      "MultiVit Syrup supports appetite, immunity, coat quality, and recovery with a complete B-complex plus vitamins A, D3, E, taurine, and lysine. The chicken-flavored syrup is readily accepted by both dogs and cats, making daily supplementation effortless for pet owners.",
    specs: [
      { label: "Composition", value: "Vitamins A, D3, E, B-complex, taurine, lysine" },
      { label: "Presentation", value: "60 mL / 120 mL bottle with dropper" },
      { label: "Dosage", value: "1 mL per 5 kg body weight daily" },
      { label: "Target Species", value: "Dogs & cats, all life stages" },
    ],
    images: [],
    brochure_url: null,
    featured: true,
    best_seller: false,
    active: true,
  },
  {
    id: "pp-4",
    slug: "groompro-oatmeal-aloe-shampoo",
    name: "GroomPro Oatmeal & Aloe Shampoo",
    category: "pet-consumables",
    subcategory: "Grooming",
    brand: "GroomPro",
    short_description:
      "Soap-free soothing shampoo for sensitive and itchy skin, salon-grade lather and scent.",
    description:
      "GroomPro Oatmeal & Aloe is a pH-balanced, soap-free shampoo that gently cleanses while soothing dry, itchy, or sensitive skin. Colloidal oatmeal and aloe vera calm irritation while pro-vitamin B5 leaves coats soft and glossy. The salon-size gallon format is a favorite of professional groomers.",
    specs: [
      { label: "Key Ingredients", value: "Colloidal oatmeal, aloe vera, pro-vitamin B5" },
      { label: "Presentation", value: "500 mL retail / 1 gal salon size" },
      { label: "pH", value: "Balanced for canine & feline skin" },
      { label: "Target Species", value: "Dogs & cats" },
    ],
    images: [],
    brochure_url: null,
    featured: false,
    best_seller: false,
    active: true,
  },
  {
    id: "pp-5",
    slug: "nutripaws-prime-adult-dog-food",
    name: "NutriPaws Prime Adult Dog Food",
    category: "pet-consumables",
    subcategory: "Pet Food",
    brand: "NutriPaws",
    short_description:
      "Premium chicken-and-rice complete nutrition with 26% protein for adult dogs.",
    description:
      "NutriPaws Prime delivers complete and balanced nutrition built on real chicken as the first ingredient, wholesome rice, and added omega-3 & 6 fatty acids for skin and coat health. Fortified with glucosamine for joint support and prebiotics for digestive health. Proudly formulated for the tropics with excellent palatability and stool quality.",
    specs: [
      { label: "Protein / Fat", value: "26% / 15%" },
      { label: "First Ingredient", value: "Real chicken" },
      { label: "Presentation", value: "3 kg / 10 kg / 20 kg bags" },
      { label: "Life Stage", value: "Adult, all breeds" },
    ],
    images: [],
    brochure_url: null,
    featured: false,
    best_seller: true,
    active: true,
  },
  {
    id: "pp-6",
    slug: "petvital-joint-plus-chews",
    name: "PetVital Joint+ Glucosamine Chews",
    category: "pet-consumables",
    subcategory: "Supplements",
    brand: "PetVital",
    short_description:
      "Tasty daily chews with glucosamine, chondroitin, and MSM for mobility and joint comfort.",
    description:
      "Joint+ combines glucosamine HCl, chondroitin sulfate, and MSM in a soft, liver-flavored chew dogs love. Supports cartilage health, mobility, and comfort in senior dogs, large breeds, and active working dogs. Visible results typically within 4–6 weeks of daily use.",
    specs: [
      { label: "Composition", value: "Glucosamine 500 mg, Chondroitin 200 mg, MSM 150 mg per chew" },
      { label: "Presentation", value: "Jar of 60 soft chews" },
      { label: "Dosage", value: "1 chew per 15 kg daily" },
      { label: "Target Species", value: "Dogs" },
    ],
    images: [],
    brochure_url: null,
    featured: true,
    best_seller: false,
    active: true,
  },
  {
    id: "pp-7",
    slug: "groompro-ear-care-solution",
    name: "GroomPro Ear Care Solution",
    category: "pet-consumables",
    subcategory: "Grooming",
    brand: "GroomPro",
    short_description:
      "Gentle ear cleansing solution that dissolves wax and keeps ears fresh between grooms.",
    description:
      "GroomPro Ear Care gently dissolves wax and debris while drying excess moisture — helping prevent the odor and irritation that lead to ear problems. Alcohol-free, sting-free formula suitable for routine use in dogs and cats, especially floppy-eared and swimming breeds.",
    specs: [
      { label: "Formula", value: "Alcohol-free cleansing & drying agents" },
      { label: "Presentation", value: "120 mL flip-top bottle" },
      { label: "Use", value: "Routine cleaning 1–2x weekly" },
      { label: "Target Species", value: "Dogs & cats" },
    ],
    images: [],
    brochure_url: null,
    featured: false,
    best_seller: false,
    active: true,
  },
  {
    id: "pp-8",
    slug: "petvital-calm-coat-omega-oil",
    name: "PetVital Calm & Coat Omega Oil",
    category: "pet-consumables",
    subcategory: "Supplements",
    brand: "PetVital",
    short_description:
      "Omega-3 rich fish oil blend for glossy coats, healthy skin, and heart support.",
    description:
      "Calm & Coat is a pure, molecularly distilled fish oil blend rich in EPA and DHA, supporting skin health, a brilliant coat, joint comfort, and cardiovascular function. Convenient pump bottle mixes easily into any meal. A simple daily upgrade recommended by veterinarians.",
    specs: [
      { label: "Composition", value: "EPA 180 mg + DHA 120 mg per pump" },
      { label: "Presentation", value: "250 mL pump bottle" },
      { label: "Dosage", value: "1 pump per 10 kg daily with food" },
      { label: "Target Species", value: "Dogs & cats" },
    ],
    images: [],
    brochure_url: null,
    featured: false,
    best_seller: false,
    active: true,
  },

  // ─── Machines & Equipment ────────────────────────────────────
  {
    id: "pe-1",
    slug: "medvet-dr900-digital-xray",
    name: "MedVet DR-900 Digital X-ray System",
    category: "equipment",
    subcategory: "Imaging",
    brand: "MedVet Imaging",
    short_description:
      "High-frequency digital radiography system with flat-panel detector, built for busy small-animal practices.",
    description:
      "The DR-900 brings hospital-grade digital radiography to veterinary practice: a 32 kW high-frequency generator, 17\" × 17\" cesium flat-panel detector, and veterinary-specific acquisition software with breed-based exposure presets. Images appear in under 3 seconds, with one-click DICOM export and cloud PACS integration. Includes installation, staff training, and a comprehensive local service warranty.",
    specs: [
      { label: "Generator", value: "32 kW high-frequency, 40–125 kVp" },
      { label: "Detector", value: "17\" × 17\" CsI flat panel, 140 μm pixel pitch" },
      { label: "Image Preview", value: "< 3 seconds" },
      { label: "Software", value: "Vet acquisition suite, DICOM 3.0, PACS-ready" },
      { label: "Table", value: "Floating 4-way table, 150 kg capacity" },
      { label: "Warranty", value: "2 years parts & service" },
    ],
    images: [],
    brochure_url: null,
    featured: true,
    best_seller: false,
    active: true,
  },
  {
    id: "pe-2",
    slug: "medvet-vetscan-ct16",
    name: "MedVet VetScan CT-16 Computed Tomography",
    category: "equipment",
    subcategory: "CT Imaging",
    brand: "MedVet Imaging",
    short_description:
      "16-slice veterinary CT scanner with rapid low-dose protocols for advanced diagnostic imaging.",
    description:
      "The VetScan CT-16 makes advanced cross-sectional imaging practical for referral hospitals and specialty practices. Sixteen-slice acquisition with veterinary low-dose protocols, a wide 70 cm bore for large-breed patients, and automated 3D reconstruction for orthopedic, oncologic, and neurologic cases. Full project support available: site planning, shielding guidance, installation, and radiologist workflow setup.",
    specs: [
      { label: "Slices", value: "16-slice helical acquisition" },
      { label: "Bore / Table", value: "70 cm bore, 200 kg carbon-fiber table" },
      { label: "Rotation", value: "0.75 s full rotation" },
      { label: "Reconstruction", value: "Real-time 3D / MPR workstation included" },
      { label: "Site Support", value: "Planning, shielding & installation included" },
      { label: "Warranty", value: "2 years parts & service, extendable" },
    ],
    images: [],
    brochure_url: null,
    featured: true,
    best_seller: false,
    active: true,
  },
  {
    id: "pe-3",
    slug: "provet-sonoview-60-ultrasound",
    name: "ProVet SonoView 60 Color Doppler Ultrasound",
    category: "equipment",
    subcategory: "Imaging",
    brand: "ProVet Diagnostics",
    short_description:
      "Portable color Doppler ultrasound with veterinary presets for abdominal, cardiac, and reproductive scanning.",
    description:
      "The SonoView 60 packs a 15.6\" full-HD display, advanced color and pulsed-wave Doppler, and species-specific presets into a 6.5 kg portable unit. Micro-convex, linear, and phased-array probes cover everything from canine abdominal studies to bovine reproductive work. Four-hour battery and one-touch image sharing make it equally at home in clinic and field.",
    specs: [
      { label: "Display", value: "15.6\" full-HD LED" },
      { label: "Modes", value: "B, M, Color, PW Doppler" },
      { label: "Probes", value: "Micro-convex, linear, phased array" },
      { label: "Battery", value: "Up to 4 hours field use" },
      { label: "Weight", value: "6.5 kg with battery" },
      { label: "Warranty", value: "1 year, extendable to 3" },
    ],
    images: [],
    brochure_url: null,
    featured: false,
    best_seller: true,
    active: true,
  },
  {
    id: "pe-4",
    slug: "labcore-hemacount-5",
    name: "LabCore HemaCount 5 Hematology Analyzer",
    category: "equipment",
    subcategory: "Laboratory",
    brand: "LabCore Systems",
    short_description:
      "5-part differential veterinary hematology analyzer — 23 parameters from a 15 μL sample in 60 seconds.",
    description:
      "HemaCount 5 delivers reference-lab quality CBCs at the point of care: a true 5-part differential across 23 parameters, from just 15 μL of whole blood, in 60 seconds. Pre-calibrated for 13 species with automatic flagging and cloud QC. Reagent bundles and preventive maintenance plans keep your cost-per-test predictable.",
    specs: [
      { label: "Differential", value: "True 5-part, 23 parameters" },
      { label: "Sample Volume", value: "15 μL whole blood" },
      { label: "Throughput", value: "60 samples/hour" },
      { label: "Species", value: "13 pre-calibrated species profiles" },
      { label: "Connectivity", value: "LIS / cloud QC, USB, LAN" },
      { label: "Warranty", value: "1 year + PM plans available" },
    ],
    images: [],
    brochure_url: null,
    featured: true,
    best_seller: false,
    active: true,
  },
  {
    id: "pe-5",
    slug: "labcore-chempro-240",
    name: "LabCore ChemPro 240 Chemistry Analyzer",
    category: "equipment",
    subcategory: "Laboratory",
    brand: "LabCore Systems",
    short_description:
      "Compact dry-chemistry analyzer for fast in-clinic organ profiles with single-slide economy.",
    description:
      "The ChemPro 240 runs comprehensive organ profiles, electrolytes, and single-test add-ons on stable dry-chemistry slides — no reagent prep, no plumbing, results in minutes. Ideal for clinics stepping up to in-house diagnostics, with pay-per-test economics and automatic result interpretation against species reference ranges.",
    specs: [
      { label: "Technology", value: "Dry-slide chemistry" },
      { label: "Menu", value: "25+ analytes, pre-bundled profiles" },
      { label: "Time to Result", value: "~ 8 minutes per panel" },
      { label: "Sample", value: "100 μL serum / plasma" },
      { label: "Footprint", value: "Benchtop, 12 kg" },
      { label: "Warranty", value: "1 year parts & service" },
    ],
    images: [],
    brochure_url: null,
    featured: false,
    best_seller: false,
    active: true,
  },
  {
    id: "pe-6",
    slug: "vettech-autoclave-s50",
    name: "VetTech AutoClave S-50 Class B Sterilizer",
    category: "equipment",
    subcategory: "Clinic Essentials",
    brand: "VetTech Instruments",
    short_description:
      "23 L Class B vacuum autoclave with automatic cycles for surgical packs and instruments.",
    description:
      "The AutoClave S-50 provides true Class B sterilization with fractionated pre-vacuum, ensuring complete penetration of wrapped instruments, hollow items, and textile packs. Five preset cycles, built-in printer for compliance records, and dual safety interlocks. The dependable heart of any surgical suite.",
    specs: [
      { label: "Chamber", value: "23 L stainless, Class B vacuum" },
      { label: "Cycles", value: "5 preset + custom programs" },
      { label: "Documentation", value: "Built-in thermal printer, USB log" },
      { label: "Safety", value: "Dual door interlock, over-pressure valve" },
      { label: "Warranty", value: "1 year parts & service" },
    ],
    images: [],
    brochure_url: null,
    featured: false,
    best_seller: false,
    active: true,
  },
  {
    id: "pe-7",
    slug: "provet-vitaltrack-monitor",
    name: "ProVet VitalTrack Multi-Parameter Patient Monitor",
    category: "equipment",
    subcategory: "Diagnostics",
    brand: "ProVet Diagnostics",
    short_description:
      "Veterinary patient monitor with ECG, SpO2, NIBP, temperature, and capnography options.",
    description:
      "VitalTrack keeps every anesthetic procedure safer with continuous ECG, SpO2, NIBP, respiration, and temperature monitoring — with optional sidestream capnography. Veterinary-specific algorithms and cuff sizes, 12\" touch display, adjustable alarms, and 72-hour trend memory. Trolley and wall mounts included.",
    specs: [
      { label: "Parameters", value: "ECG, SpO2, NIBP, RESP, TEMP (+ EtCO2 option)" },
      { label: "Display", value: "12\" color touch screen" },
      { label: "Trends", value: "72-hour graphical & tabular" },
      { label: "Power", value: "Mains + 4-hour battery backup" },
      { label: "Warranty", value: "1 year parts & service" },
    ],
    images: [],
    brochure_url: null,
    featured: false,
    best_seller: true,
    active: true,
  },
  {
    id: "pe-8",
    slug: "vettech-anesthiacare-v2",
    name: "VetTech AnesthiaCare V2 Anesthesia Machine",
    category: "equipment",
    subcategory: "Clinic Essentials",
    brand: "VetTech Instruments",
    short_description:
      "Precision isoflurane/sevoflurane anesthesia system with ventilator-ready circuit for small animals.",
    description:
      "AnesthiaCare V2 delivers smooth, precise anesthesia with a calibrated dual-agent vaporizer mount, fine-control flowmeters, and both rebreathing and non-rebreathing circuits for patients from 200 g to 100 kg. Ventilator-ready with standard connections and an integrated safety pop-off with manometer. Trusted in hundreds of Philippine surgical suites.",
    specs: [
      { label: "Vaporizer", value: "Isoflurane or Sevoflurane, TEC-compatible" },
      { label: "Patient Range", value: "200 g – 100 kg" },
      { label: "Circuits", value: "Rebreathing + Bain non-rebreathing" },
      { label: "Safety", value: "Pop-off valve with manometer, O2 flush" },
      { label: "Warranty", value: "1 year parts & service" },
    ],
    images: [],
    brochure_url: null,
    featured: true,
    best_seller: false,
    active: true,
  },
];
